module.exports = {
    login: '/user/login',
    googleLogin: '/user/googlelogin',
    register: '/user/register',
    logout: '/user/logout',
    info: '/user/info',
    getClasses:'/class/me',
    getClassById:'/class/me/',
    getGrade:'/grade/:id',
    getMyGrade:'/grade/me',
    createClass: '/class/create',
    changePassword: '/user/changepassword',
    changeProfile: '/user/changeprofile',
    authenticate: '/user/authenticate',
    invite: '/class/invite',
    verify:'/class/invite/verify',
    updateAssignment:'/class/update-assignment',
    uploadStudentList: '/class/:classId/import',
    downloadStudentList: '/class/:classId/export',
    showStudentGradeList: '/class/:classId/grade',
    updateStudentId: '/user/updateStudentId',
    markAsDone: '/grade/:classId/:assignmentId/isDone',
    exportGradeBoard: '/class/:classId/grade/download',
    downloadAssignmentGrade: '/grade/:classId/:assignmentId/export',
    uploadtAssignmentGrade: '/grade/:classId/:assignmentId/import',
    updateStudentAssignmentGrade: '/grade/:classId/:assignmentId/:studentId'
}